artifact_uri: ./mlruns/1/675443150d1c42e7bd455ad5cc39963f/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 675443150d1c42e7bd455ad5cc39963f
run_uuid: 675443150d1c42e7bd455ad5cc39963f
source_name: ''
source_type: 4
source_version: ''
start_time: 1713093173992
status: 1
tags: []
user_id: root
