artifact_uri: ./mlruns/1/2283d543aec246dd87cb7003deeea3c4/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 2283d543aec246dd87cb7003deeea3c4
run_uuid: 2283d543aec246dd87cb7003deeea3c4
source_name: ''
source_type: 4
source_version: ''
start_time: 1713093174592
status: 1
tags: []
user_id: root
