artifact_uri: ./mlruns/1/ac5cd527720b4cc4911d63ab56c925f2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: ac5cd527720b4cc4911d63ab56c925f2
run_uuid: ac5cd527720b4cc4911d63ab56c925f2
source_name: ''
source_type: 4
source_version: ''
start_time: 1713093044636
status: 1
tags: []
user_id: root
