artifact_uri: ./mlruns/1/d8119badf91b4f6280018d93f6d55c9e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: d8119badf91b4f6280018d93f6d55c9e
run_uuid: d8119badf91b4f6280018d93f6d55c9e
source_name: ''
source_type: 4
source_version: ''
start_time: 1713093174296
status: 1
tags: []
user_id: root
