artifact_uri: ./mlruns/1/6abd7c6e03314982bb9f6e0f0b4293c9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 6abd7c6e03314982bb9f6e0f0b4293c9
run_uuid: 6abd7c6e03314982bb9f6e0f0b4293c9
source_name: ''
source_type: 4
source_version: ''
start_time: 1713093173361
status: 1
tags: []
user_id: root
